server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carbon
    username: root
    password: 889915
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


